### PR TITLE
Adds nifty feature to evolve choropleth in time.

### PR DESCRIPTION
**Pull request by magixsno**
Hello daenuprobst!

I'm a fan of your work. In this PR I've added a feature to the cantonal map: A play button at the bottom which will evolve the map at 3 fps through each day of the pandemic for the selected data point (defaulting to cases). 

Screen Shot 2020-11-25 at 2 30 06 PM

A few design choices:
* The dates are also localized according to the provided language -- since country is unavailable, I assume Swiss. 
* Without fixing the colorAxis bar, the bar tends to jump around making the "progress through time" effect I was aiming for difficult to read. When fixing the colorAxis bar, because the most recent surge in cases/hospitalizations is so high, the result was the map just dully remaining blue through time until ~Oct -- I decided to adjust the colorAxis when the play button is playing to include the darker shade of red to make the playthrough more visually interesting. 
* The max-range at which to fix the colorAxis is unfortunately hard coded -- one could iterate through all the days to find the maximum associated with the particular facet, but I decided the latency implications were not worthwhile and instead hardcoded the values.
* I decided not to change the "Today's Data" header and correspondingly left default behavior for the map on page load identical. The user could find this confusing if they mess with the toggle and the header still reads "Today's Data" but I'm not sure if that's a major issue.
* I chose 2020 Feb 27 as the "beginning of the pandemic" for the sake of this graphic. At this point was when multiple cantons start having consistent data.
* I tried my best to mimick the color scheme with the play slider.

_Merci vilmal 🤡_ 

Best,
magixsno

### CODE REVIEW

**Comment by daenuprobst** [comment]
Hey, Thanks for that one. Will give it a go locally before merging (currently a bit busy).

**Comment by daenuprobst** [comment]
Ok, that's neat! Could you make a few changes first though?
- Make the control span the whole width of the card for design purposes)
- Add a button to get back to the current date
- The slider only seems to go to yesterday

(Sorry again for the late reply, I have been busy work-wise)

**Comment by magixsno** [comment]
Thank you for your response, all the things you point out are good points.

1. The control bar has been updated to be dynamic in size to fit the width of the choropleth cell. This has made the html a slight more complex as a result in order to maintain cross-browser & window-size compatibility.

2. A 'fast forward' style button has been added which will jump to the date of today.

3. Thank you for pointing out the off-by-one error in the play slider bar, that has been resolved.

Additionally, I cleaned up a quick error I ran into where the page would fail to load if the browser did not provide a user language, because the date to populate next to the slider bar would fail without a proper locale. I've resolved this issue as well.

**Comment by magixsno** [comment]
I fixed one last issue I ran into where the skip to today button didn't interact well if we were already in 'play' mode. That has been resolved -- if a user hits the skip to today button, then we cease to play if we are playing.

**Comment by magixsno** [comment]
Hello! I hope your holiday has gone well. Please let me know if you have any other changes you'd like to see to this PR. 😄

**Comment by magixsno** [comment]
Hello daenuprobst! Would you like me to revise this PR?

**Pull request closed without merging**
